### ISSUE TITLE
add workspace ID option for experiments

### ISSUE THREAD

**Issue by VictorMorand** [experimaestro/experimaestro-python#119]
instead of setting  it manually with  `experimaestro run-experiment ... --workspace YOUR_ID` 
It would be nice to have the possibility to provide the workspace id in an experiment parameters file param.yaml, 
such as
```yaml
id: my_id          #id of the experiment
title: "Some xp"
description: " ... "
file: myXpFile
workspace: myworkspace_ID
# or optionnally 
workdir: "path/to/workdir" # this is also an option of `experimaestion run-experiment `
```
